language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 14026f0d1d2d2b30c10e146508a3ec11a2c3e146
    token:
      secure: op8vpR6xDLhMlB2CsYnt9ThGm6gmlY6hPDCzkDcLBWiH4R0i2OvqGdIPV2d/MajUlXUeXfUPqZal4+FMnyyKBv9cmwqK2git78+E/uOg421H46WO0R0N9H8acoZrkMLkpqf19bokYjTqFTTRHrfFuSuqMeu32BzPbZN21C9EzNavXpH8ZrYPpVhktCa6ChFWGH1IsHMKQ/816g9dPDwPKZlTddA1ZqT4iDAn5jgu0AI/cZq8BpqQJF8ECl8AGmFnGhV3g3c7PVfMOvn9huZvGeG+w+3PFOaGs4cD+A4H+k2MWXN5aRXEF8VKXna2NaauDOXq5IvkeTRjp6hwzPirei4w2q9q61kKNQR0rVjygJikSgKeO1jGvmzlUcJr1OY2IyN35Qx1K5aN4ds0IXz4moAYjRspuQ9XNYa0RvRKdCDqcIT4YU5coxq6eKznpYysgpWmhw/M6ezbtAwPtcAyey//7tf+HloT3z7k7n7qTxIAnXmBmP4EvJQ2Txl4leOR/aSno/N7hQChowSi2Z4FHxSt8f2hDmxoAdAPncbFqB+M9yJUDHVH2j5BVTq75Aiy15nrAjdQi2J4GimmcU//2GwtcFhaITwqEChizdliMXm33ySJAiT6Abg0mZV9Dg1/FmONdPQfk2xM3MP98jqEVw2VysMNfFrC10jt0SxvZKQ=
jdk:
- oraclejdk8
script:
- ./gradlew sonarqube
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle
env:
  global:
    secure: op8vpR6xDLhMlB2CsYnt9ThGm6gmlY6hPDCzkDcLBWiH4R0i2OvqGdIPV2d/MajUlXUeXfUPqZal4+FMnyyKBv9cmwqK2git78+E/uOg421H46WO0R0N9H8acoZrkMLkpqf19bokYjTqFTTRHrfFuSuqMeu32BzPbZN21C9EzNavXpH8ZrYPpVhktCa6ChFWGH1IsHMKQ/816g9dPDwPKZlTddA1ZqT4iDAn5jgu0AI/cZq8BpqQJF8ECl8AGmFnGhV3g3c7PVfMOvn9huZvGeG+w+3PFOaGs4cD+A4H+k2MWXN5aRXEF8VKXna2NaauDOXq5IvkeTRjp6hwzPirei4w2q9q61kKNQR0rVjygJikSgKeO1jGvmzlUcJr1OY2IyN35Qx1K5aN4ds0IXz4moAYjRspuQ9XNYa0RvRKdCDqcIT4YU5coxq6eKznpYysgpWmhw/M6ezbtAwPtcAyey//7tf+HloT3z7k7n7qTxIAnXmBmP4EvJQ2Txl4leOR/aSno/N7hQChowSi2Z4FHxSt8f2hDmxoAdAPncbFqB+M9yJUDHVH2j5BVTq75Aiy15nrAjdQi2J4GimmcU//2GwtcFhaITwqEChizdliMXm33ySJAiT6Abg0mZV9Dg1/FmONdPQfk2xM3MP98jqEVw2VysMNfFrC10jt0SxvZKQ=
