language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 14026f0d1d2d2b30c10e146508a3ec11a2c3e146
jdk:
- oraclejdk8
script:
- sonar-scanner
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle