language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 14026f0d1d2d2b30c10e146508a3ec11a2c3e146
    token:
      secure: VYDMfC1I7hZ0htdI36if0+d+6V661Iw23M5jJE7dZ2pPb+C7GLSuyb20TLOXLKY5N5KWk4ICuITMxDqnTYpXZkMcK2d3YrwCd7MDzGzF+V/dH+iJ10IOf1ltNN0jhZggPS/rspJPBY9OTb2KWTkno7FaKUyUKNX220tuM2PY0UXtQGKkE769StZ93MOrTTrhUzDTu9hMGsLFmoVz3n7K2ISOmHl2oqgCDTgujDrgrWOFmF1P0bRDgsAC68NAuYUlUJF4GS3YsrJIrECF6hNh71ozp5YLCyEPFllA34QnsEcPa7BNspspbm7udm8xuf9vVoFZUv+uFy9or1A17WPKyaSTea0A1GJoamQFYsZ93Z74SbP1VvcFOGvVqN1XXsbJjCRHjyj3mujznKNqcyWUm24iKGMRkwseVi/Sg1iWkJm5tsYuRnMDnW3IfYuvLVvbY1w/ONk+xtZ1i5ng+8/N24d0N4kKvSbV3osPB0vpHcpJaHmKHSp2CffVL0iC8hN6I8F5E5w58c6yojoRNQvQ/0PMC4ONK+RVo9RginNka/LOjKyfwBrND0lGSRp2WGTVKWEVMetKp/nXo4gmOCKjtcTeN2EAyAhQjsH5FMEAcRZncb1CmeQe3TbaByYl8+8VUxuboqDZ0R4bp0PTtvdUqlCXY3QJ37mtyl36wzW9yFw=
jdk:
- oraclejdk8
script:
- sonar-scanner
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.sonar/cache
  - $HOME/.gradle
  - .gradle